name: Go
on: push
env:
  GO111MODULE: on
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
        - '1.18'
        - '1.19'
        - '1.20'
        - '1.21'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: go test -race -cover
