name: Go
on: push
env:
  GO111MODULE: on
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
        - '1.21'
        - '1.22'
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - run: go test -race -cover
